export default {
  exportBtnInExportSettings: '.export-btn',
  emailSentConfirmationModal: '.email-sent-block',
  indentedRadioBtn: 'input[value="indented"]',
  firstLevelOnlyInExportSettings: '.radio.large input[value="shallow"]',
  sourcingCheckBoxes: '.export-depth.sourcing-block [type="checkbox"]',
  includeManufacturersCheckBox: '//span[text()="Include Manufacturers"]//preceding-sibling::input[@type="checkbox"]',
  includeDocuments: '#routes input[name="details"]',
  customizeFieldsIcon: '.file-to-include .customize-fields',
  customizeFieldsCheckBoxes: '.customise-specifications-table-content [type="checkbox"]',
  levelFieldCheckBx: '[name="Level"] input[type="checkbox"]',
  saveBtnInCustomizeFieldsModal: '//button[text()="SAVE"]',
  selectDocumentTypesIcon: '.documents-to-include .customize-fields ',
  selectDocumentTypesCheckBoxes: '.customise-documents-table-cotent [type="checkbox"]',
  genericFieldCheckbx: '[name="GENERIC"] input[type="checkbox"]',
  saveBtnInSelectDocument: '//button[text()="SAVE"]',
  ccEmail: '[placeholder="Enter email addresses (separate by commas)"]',
  saveTemplateIcon: '.export-side-area [data-tip="Save Template"]',
  dropdownIndicator: '.export-right-side-area div.duro__dropdown-indicator',
  defaultSettings: '//div[text()="Default Settings"]',
  cancelBtn: '//button[text()="CANCEL"]',
  templateDropdown: '//div[contains(@class,duro_menu)]//div[text()="category"]//parent::div//div[text()="templateName"]',
  TemplateNameInSaveAsNewTemplate: '[name="save-template"]',
  saveBtnInSaveOrUpdateTemplateModal: '.spinner-btn',
  saveBtnInCustomizeFieldsModal: '//button[text()="SAVE"]',
  downloadRadioBtn: 'input[value="download"]',
  checkAllCheckBoxes: 'input[name="check-all"]',
  accessibleToAllCheckBx: 'input[name="check-row"]',
  saveOrUpdateTemplateModal: '.modal-content h2',
  ccMailTextArea:'//div[@class="mail-block"]//textarea[@placeholder="Enter email addresses (separate by commas)"]',
  dropdownIndicatorInSaveOrUpdateModal: '//div[@class="existing-templates"]/child::div//div[contains(@class,"duro__indicators")]',
  exportTable: '#export-table',
  docType: '[name="docType"]',
  flattenedRadioBtn: 'input[value="flattened"]',
  componentCheckboxInAddComponents: '//span[text()="name"]/ancestor::li//input[@type="checkbox"]',
  addBtnInExportPage: 'button.btn-add',
  exportLoadingSpinner: '.notification-loader svg'
}
