export default {
  assemblyOptn: 'div[name="assembly"]',
  editIconInTable: '.add-trigger[data-tip="Edit"]',
  addIconInTable: '.selected button[data-testid="duro-menu-button-assembly"]',
  addFromLibraryOptn: '//span[text()="Add from Library"]',
  addBtnInAddComponents: '.btn-add',
  componentCheckboxInAddComponents: '//span[text()="CPN"]/ancestor::li//input[@type="checkbox"]',
  settingsDropDownOption: '//span[text()="CPN"]/ancestor::li//input[@type="checkbox"]',
  assemblyTableInputFiled: '//*[text()="cpn"]//ancestor::tr//input[@name="quantity"]',
  assemblyErrorReport: '.tabs-headings .error-text',
  tableCellSelector: '#assemblyEdit tbody tr:nth-child(#rowNum) input[name="#columnName"]',
  deleteBtnSelector: '#assemblyEdit > tbody > tr:nth-child(#rowNum) > td.remove-col',
  searchField: 'input.search-input',
  closeIconInAddComponents: '.close-icon',
  statusValueInAssemblyTable: '//*[text()="name"]//ancestor::tr//span[@class="status-value"]',
  addCmpOptionsModalInAssemblyTable: '[data-testid="duro-menu-list-assembly"]',
  addAnotherCheckBx: '//input[@name="add_more"]',
  successNotificationToast: '.cmp-success-popover',
  closeOptnInCreateManually: '//div[@class="buttons modal-close"]//*[name()="svg"]',
  addFromVendoroptn: '//span[@data-tip="Add from vendor"]',
  errorCountInAssemblyTab: '//div[@class="tab-text-error"][text()="errorCount"]',
  importFromFileIcon: '.assembly-tab [data-tip="Import components from file"]',
  fileUpload: '//a[@class="browse"]//ancestor::div[@class="drop-zone"]//input[@type="file"]',
  updateFromExistingLibrary: 'input[value="update_assembly"]',
  tableHeader: 'th[name="cpn"]',
  quantityInAssemblyTable: '//span[@class="cpn-value" and text()="CPN"]//ancestor::tr//span[@class="quantity" and text()="Quantity"]',
  refDesInAssemblyTable: '//span[@class="cpn-value" and text()="CPN"]//ancestor::tr//span[@class="refDes" and text()="RefDes"]',
  createManually: '//span[@data-tip="Create manually"]',
  assemblyChildCount: '//table[@id="extended-table-data"]//tbody',
  cancelBtnInCreateManuallyPage: '.dark',
  componentCheckboxWithIndex: (index) => `.list-area ul li:nth-child(${index}) input`,
  assemblyChildCmp: '//td//*[text()="name"]',
  assemblyLibraryCpn: '.list-area .cpn',
  assemblyCmpsCount: '.assembly-tab .records-count',
  addFromFileIcon: '[data-tip="Import components from file"]',
  gridViewIcon: 'span.grid-view',
  treeViewIcon: 'span.tree-view',
  tableCellInAssemblyTable: '//span[text()="name"]/ancestor::tr//*[@class="quantity"]',
  assemblyTable: '.assembly-list-tree #extended-table-data tbody',
  expandIcon: 'div.assembly-list-tree span.tree-expand-icon',
  collapseIcon: 'div.assembly-list-tree span.tree-collapse-icon',
  treeViewTable: ".assembly-list-tree",
  expandOptn: '//span[contains(text(),"Expand")]', 
  gridViewTable: ".assembly-list",
  variantIcon: '//*[text()="cmpName"]/ancestor::td//div[@class="variant-holder"]',
  rolledUpModifiedIcon: 'div[data-tip="1 or more child components have been modified"]',
  expandTriangleIcon: '//*[text()="cmpName"]/preceding-sibling::span/div',
  expandTriangleIconInCompareRevisionPage: '//*[text()="cmpName"]//div',
  chooseCategory: '.modal [name="category"] select'
}
