export default {
  capacitor: {
    specLabel: '//label[text()="labelName"]',
    capacitance: '//label[text()="Capacitance"]//following-sibling::input',
    voltage: '//label[text()="Voltage"]//following-sibling::input',
    tolerance: '//label[text()="Tolerance"]//following-sibling::input',
    package: '//label[text()="Package"]//following-sibling::select',
    type: '//label[text()="Type"]//following-sibling::select',
    mountStyle: '//label[text()="Mount Style"]//following-sibling::select',
    materialClass: '//label[text()="Material Class"]//following-sibling::select',
    polarity: '//label[text()="Polarity"]//following-sibling::select',
    maxHeight: '//label[text()="Max Height"]//following-sibling::input',
    operatingTemparatureMax: '//label[text()="Operating Temperature Max"]//following-sibling::input',
    capacitanceInCmpEditPage: '//span[text()="Capacitance"]//following-sibling::div/input',
    packageInCmpEditPage: '//span[text()="Package"]//following-sibling::div/select',
    voltageInCmpEditPage: '//span[text()="Voltage"]//following-sibling::div/input',
    toleranceInCmpEditPage: '//span[text()="Tolerance"]//following-sibling::div/input',
    typeInCmpEditPage: '//span[text()="Type"]//following-sibling::div/select',
    opTempMaxInCmpEditPage: '//span[text()="op temp (max)"]//following-sibling::div/input',
    mountStyleInCmpEditPage: '//span[text()="Mount Style"]//following-sibling::div/select',
    materialClassInCmpEditPage: '//span[text()="Material Class"]//following-sibling::div/select',
    maxHeightInCmpEditPage: '//span[text()="Max Height"]//following-sibling::div/input',
    polarityInCmpEditPage: '//span[text()="Polarity"]//following-sibling::div/select',
    massInCmpEditPage: '//span[text()="MASS (g)"]//following-sibling::div/input',
    procurementInCmpEditPage: '//span[text()="procurement"]//following-sibling::select',
    unitOfMeasureInCmpEditPage: '//span[text()="unit of measure"]//following-sibling::select',
    specFieldsInViewCmpPage: '//span[text()="name"]//following-sibling::span',
    packageDropdownValues: '//label[text()="Package"]//following-sibling::select/option',
    typeDropdownValues: '//label[text()="Type"]//following-sibling::select/option',
    mountStyleDropdownValues: '//label[text()="Mount Style"]//following-sibling::select/option',
    materialClassDropdownValues: '//label[text()="Material Class"]//following-sibling::select/option',
    polarityDropdownValues: '//label[text()="Polarity"]//following-sibling::select/option',
  },
  resistor: {
    resistance: '//label[text()="Resistance"]/following-sibling::input',
    tolerance: '//label[text()="Tolerance"]/following-sibling::input',
    package: '//label[text()="Package"]/following-sibling::select',
    power: '//label[text()="Power"]/following-sibling::input',
    mountStyle: '//label[text()="Mount Style"]/following-sibling::select',
    technology: '//label[text()="Technology"]/following-sibling::select',
    tempCoefficient: '//label[text()="Temperature Coefficient"]/following-sibling::input',
    voltageRating: '//label[text()="Voltage Rating"]/following-sibling::input',
    packageDropdownValues: '//label[text()="Package"]/following-sibling::select/option',
    mountStyleDropdownValues: '//label[text()="Mount Style"]/following-sibling::select/option',
    technologyDropdownValues: '//label[text()="Technology"]/following-sibling::select/option',
  },
  errorToolTip: '//input[@data-tip="ErrorMsg"]',
}
