export default {
  tableHeader: 'th[name="cpn"]',
  sourcingTab: 'div[name="sourcing"]',
  tableCellValue: '//td//input[@value="value1" and @name="key"]',
  selectAlloptn: 'input[type="checkbox"][name="selectAllMFR"]',
  expandOptn: '//span[contains(text(),"Expand")]', 
  updateOptn: 'span.update',
  selectFirstRow: 'tbody tr:nth-child(1) td:nth-child(1) div:nth-child(1)', 
  updateLoaderHeading: ' .validation-heading h4',
  unitPriceGreenIcon: '[name="unitPrice"] ~ .unitPrice-icon [id="Verified"]',
  leadTimeGreenIcon: '.leadtime-inner-style [id="Verified"]',
  tableCell: '#extended-table-data tr:nth-child(rowIndex) td:nth-child(headerIndex)',
  tableRows: '#extended-table-data tr',
  selectAllQuotesInDistributor: '.select-all-qoutes.man-1.dist-1 input[type="checkbox"]',
  selectAllDistributors: '.select-all-distributors.man-1 input[type="checkbox"]',
  selectAllQuotes: '[name="selectAllQuotes"]',
  middleMfrCheckBx: '.mfrCheckBox .middle',
  middleDistributorCheckBx: '.select-all-distributors .middle', 
  quoteCheckboxInDistributor: '.man-1.dist-1.quote-1 input[type="checkbox"]',
  setPrimaryOptn: '//span[text()="Set Primary"]',
  primarySourceQuoteCheckbox: '.man-1.dist-1.quote-1 .primarySource',
  unitPriceField: 'input[name="unitPrice"]',
  unitPriceRedUpIcon: '[name="unitPrice"] ~ .unitPrice-icon [id="Up"]',
  leadTimeRedUpIcon: '.leadtime-icon-style [id="Up"]',
  leadTimeField: 'input[name="leadTime"]',
  unitPriceGreenDownIcon: '.unitPrice-icon [id="Down"]',
  leadTimeGreenDownIcon: '.leadtime-icon-style [id="Down"]',
  unitPriceGreenCheckMark: '.man-1.dist-1.quote-1 .unitPrice-style  #Verified',
  leadTimeGreenCheckMark: '.man-1.dist-1.quote-1 .leadtime-icon-style #Verified',
  unitPriceIcon: '.man-1.dist-1.quote-1 .unitPrice-style .ui-icon',
  leadTimeIcon: '.man-1.dist-1.quote-1 .leadtime-icon-style .ui-icon',
  viewSourcing: {
    tableHeader: '[name="distName"]',
    primarySourceCheckbox: '.center-state.checkbox.active',
    checkBox: '(//tbody//span[contains(@class,"index-checkbox")])[rowIndex]//input',
    commonCheckBx: 'span.index-checkbox.block input[type="checkbox"]',
    greenCheckMark: '#extended-table-data tbody tr:nth-child(rowIndex) td:nth-child(headerIndex) #Verified',
    greenDownArrow: '#extended-table-data tbody tr:nth-child(rowIndex) td:nth-child(headerIndex) [id="Down"]',
    redUpArrow: '#extended-table-data tbody tr:nth-child(rowIndex) td:nth-child(headerIndex) [id="Up"]',
    tableCellValue: '#extended-table-data tbody tr:nth-child(rowIndex) td:nth-child(headerIndex) .data-value',
    checkMarkAndArrowIcon: '#extended-table-data tbody tr:nth-child(rowIndex) td:nth-child(headerIndex) .ui-icon',
    rolledUpCostCheckbox: (index) => `(//div[contains(@class, "rolled-up-cost-table")]//td[contains(@class, "indexes")])[${index}]`,
  },
  editSourcing: {
    addManufacturer: 'div[data-tip="Add new manufacturer"]',
    removeIcon: (name) => `//input[@data-input-value="${name}"]//ancestor::tr//td[@class="remove-col"]`,
    quoteRemoveIcon: (man, dist, quote) => `.man-${man}.dist-${dist}.quote-${quote} .remove-col div`,
    manufacturerData: {
      MPN: (man) => `.man-${man} [name="mpn.key"]`,
      manufacturerName: (man) => `.man-${man} [name="manufacturer-name"]`,
      manufacturerDes: (man) => `.man-${man} [name="manufacturer-description"]`,
      manufacturerWarranty: (man) => `.man-${man} [name="warranty"]`,
    },
    distributorData: {
      DPN: (man, dist) => `.man-${man}.dist-${dist} [name="dpn.key"]`,
      distributorName: (man, dist) => `.man-${man}.dist-${dist} [name="name"]`,
      distributorDes: (man, dist) => `.man-${man}.dist-${dist} [name="description"]`,
    },
    quoteData: {
      leadTimeUnit: (man, dist, quote, unit) => `.man-${man}.dist-${dist}.quote-${quote} [value="${unit}"]`,
      minQuantity: (man, dist, quote) => `.man-${man}.dist-${dist}.quote-${quote} [name="minQuantity"]`,
      unitPrice: (man, dist, quote) => `.man-${man}.dist-${dist}.quote-${quote} [name="unitPrice"]`,
      leadTime: (man, dist, quote) => `.man-${man}.dist-${dist}.quote-${quote} [name="leadTime"]`,
    },
    ErrorToolTip: (assertText) => `//div[@data-tip="${assertText}"]`,
    addNewQuote:"[data-tip='Add new quote']",
    unitPriceValue: ".diff-unit-price-section .inner-value span",
    rolledUpCostTable: ".rolled-up-cost-table",
    customQuote: (row) => `.sourcing-list-view #index-table tbody tr:nth-child(${row}) span`,
    errorCount: '[name="sourcing"] .tab-text-error'
  },
}
