export default {
  newBtn: 'a.new-button',
  tableCell: '//tr//*[text()="name"]/ancestor::tr//td[index]',
  tableCellContains: '//tr//*[contains(.,"name")]/ancestor::tr//td[index]',
  tableRow: '//tr//*[text()="name"]/ancestor::tr',
  tableHeader: 'th[name="cpn"]',
  tableIndexes: '//table[@id="index-table"]//tbody//tr[indexValue]//input',
  loadingSpinner: '.ui-loading',
  settingsDropdown: '.table-settings-wrapper',
  settingsDropDownOption: '//span[text()="CPN"]/ancestor::li//input[@type="checkbox"]',
  revisionValue: '//*[text()="name"]//ancestor::tr//span[@class="revision-value"]',
  searchField: '[placeholder="Enter a search term or query"]',
  weFoundTheFollowingErrorModal: '//p[text()="We found the following error(s)"]',
  duplicateProdOrCompInSearchPage: '//span[contains(text(),"Copy")]',
  newProduct: {
    categoryItem: 'input[value="Electrical"]',
    productName: '[name="name"]',
    lifeCycleStatus: 'select[name="status"]',
    eid: '[name="eid"]',
    productDescription: 'textarea[name="description"]',
    productTeamEmail: '//td[text()="QA"]/following-sibling::td//input',
    emailForProductManager: '//td[text()="Product Manager"]/following-sibling::td//input',
    emailForEngineering: '//td[text()="Engineering"]/following-sibling::td//input',
    emailForQA: '//td[text()="QA"]/following-sibling::td//input',
    preProductionTragetDate: '//td[text()="Pre-Production"]/following-sibling::td[@class="forecast-date"]//input',
    preProductionVolume: '//td[text()="Pre-Production"]/following-sibling::td/input[@name="forecastsVolume"]',
    massProductionTragetDate: '//td[text()="Mass Production (Launch)"]/following-sibling::td[@class="forecast-date"]//input',
    massProductionVolume: '//td[text()="Mass Production (Launch)"]/following-sibling::td/input[@name="forecastsVolume"]',
    addNewForecast: '.add-forecast',
    uploadThumbnails: '.thumbnails-block input',
    fileUploadProgress: '.file-uploading .current-progress i',
    cancelFileUpload: '.file-uploading .cancel-file',
    uploadDocuments: '.documents-block input',
    fileNameWhileUploading: '.upload-file-list .file-name',
    createBtn: '[type="submit"]',
    fileUploadError: '.file-upload-error span',
    deleteIconForFailedFile: '//*[text()="File exceeds 25mb limit"]//parent::div//div[@class="delete-icon"]',
    deleteIcon: 'form #SMALL-REMOVE',
    revisionTooltip: '.rev-block div input',
    productForecast: '.forecasting-block tbody tr:not(.add-row)',
    revision: 'input[name="revision"]',
    newProductPage: '#routes',
  },
  editProductIcon: '.cta-icon-toolbar [data-tip="Edit product information"]',
  editProd: {
    productName: '[name="name"]',
    productDescription: 'textarea[name="description"]',
    eid: 'input[name="eid"]',
    cpnValue: '.edit-cpn-field',
    statusDropdown: 'select[name="status"]',
    thumbNailUpload: '.dropzone-container input[type="file"]',
    mpnValue: '.diff-mpn-section .inner-value',
    mfrValue: '.diff-mfr-section .inner-value',
    minQty: '.diff-min-qty-section .inner-value',
    unitPrice: '.diff-unit-price-section .unit-price',
    leadtime: '.diff-lead-time-section .inner-value',
    massField: 'input[name="mass"]',
    procurement: 'select[name="procurement"]',
    teamField: '//*[text()="Engineering"]/following-sibling::input',
    preProductionTragetDate: '//span[text()="Pre-Production"]/following-sibling::div/div[@class= "schedule-date"]//input',
    preProductionVolume: '//span[text()="Pre-Production"]/following-sibling::div/div[@class= "schedule-amount"]//input',
    massProductionTragetDate: '//span[text()="Mass Production (Launch)"]/following-sibling::div/div[@class= "schedule-date"]//input',
    massProductionVolume: '//span[text()="Mass Production (Launch)"]/following-sibling::div/div[@class= "schedule-amount"]//input',
    saveBtn: '#routes .banner-block [value="SAVE"]',
    documentsTab: '.tabs-block [name="documents"]',
    uploadDocuments: '//span[text()="Or browse"]//ancestor::div[@class="drop-zone"]//input[@type="file"]',
    fileUploadProgress: '#documentsTable .file-uploading',
    fileUploadError: '.file-upload-error .current-status',
    cancelFileUpload: 'span.cancel-file',
    productForecastInBuildSchedule: '.schedule-edit',
    addForecastInBuildSchedule: '.add-schedule',
    cancelBtn: '.delete_btn',
    errorIcon: '[class="error-alert"]',
    saveAsRevisionBtn: '//div[@class="banner-block"]//button[text()="SAVE AS REVISION"]',
    editModeBannerBlock: '.banner-block',
    cancelBtnInEditProduct: '//div[@class="banner-block"]//a[text()="CANCEL"]',
    erpStartDate: '//span[text()="Start Date"]/following-sibling::div//input',
    erpEndDate: '//span[text()="End Date"]/following-sibling::div//input',
    erpToolTip: '//div[@class="react-datepicker__input-container"]//input["assertText"]',
    revisionInSaveAsRevisionModal: 'input[name="revision"]',
    continueBtnInSaveAsRevisionModal: '.filled',
    erpMessage: '.erp-message',
    commentInBulkUpdateSaveAsRevisionModal: '[name ="revision-comment"]',
    continueBtnInSetNewRevisionsModal: '.spinner-btn.btn-header.active',
    name: '.name-block [name="name"]',
  },
  viewProduct: {
    prodName: '.truncate-name',
    cpnValue: '.tile-item .cpn-value',
    eidValue: '.eid-info',
    revisionValue: 'div.diff-revision-section span.revision-value',
    statusLabel: 'div.diff-status-section span.status-label',
    prodDesc: '.tile-item .description',
    mpnValue: '.diff-mpn-section .inner-value',
    mfrValue: '.diff-mfr-section .inner-value',
    minQty: '.diff-min-qty-section .inner-value',
    unitPrice: '.diff-unit-price-section .inner-value',
    leadTime: '.diff-lead-time-section .inner-value',
    massValue: '.diff-mass-cell-section .inner-value',
    procurementValue: '.diff-procurement-cell-section .inner-value',
    createdDate: '//span[text()="created"]/following-sibling::div//span[@class="date-span"]',
    modifiedDate: '//span[text()="modified"]/following-sibling::div//span[@class="date-span"]',
    modifiedBy: '.created-by',
    productManagerTeamEmail: '//*[text()="product manager"]/following-sibling::a',
    engineeringTeamEmail: '//*[text()="engineering"]/following-sibling::a',
    qaTeamEmail: '//*[text()="quality assurance (qa)"]/following-sibling::a',
    procurementTeamEmail: '//*[text()="procurement"]/following-sibling::a',
    manufacturingTeamEmail: '//*[text()="manufacturing"]/following-sibling::a',
    preProductionDate: '.diff-preproduction-section .date-span',
    preProductionVolume: '.diff-preproduction-section .schedule-amount span',
    massProductionDate: '.diff-massproductionlaunch-section .date-span',
    massProductionVolume: '.diff-massproductionlaunch-section .schedule-amount span',
    deleteIcon: '#delete-svg',
    deleteProductModal: '.modal-content',
    deleteBtn: 'button.danger',
    productsTableRows: '.index-table tbody tr',
    procurementDropdown: '.inner-info.values-to-right.diff-procurement-section select',
    productForecast: '.schedule',
    historyIcon: '//div[@data-tip="View product revisions"]',
    revisionHistoryTable: '#rev-history-table tbody tr div.arrow-button',
    changeOrderIcon: '//span[text()="Change Order"]',
    erpTile: '//*[text()="ERP"]/ancestor::aside[@class="tile-item"]',
    erpStartDate: '//span[text()="Start Date"]//parent::div//span[@class="date-span"]',
    erpEndDate: '//span[text()="End Date"]//parent::div//span[@class="date-span"]',
    erpType: '//span[text()="Item Type"]//following-sibling::span',
    reportsTab: '[name="reports"]',
    massUnitLabel: '.diff-mass-cell-section .inner-attribute',
    exportIcon: '.navigation .ui-icon[data-tip="Export this product"]',
    erpMessage: '.erp-message',
    historyTableLoadingIcon: 'div.loading-block .ui-icon',
    subRevisionLazyLoading: 'tr.custom-loader-holder',
    previousRevision: '//div[@class="custom-history-table"]//tbody/tr[index]/td[3]//span[@class="user-name"]',
    historyIconInCompareRevisionPage: '.revision-col.modified-col .icon-holder .ui-icon',
    revisionHistoryIcon: '#rev-history-table .ui-icon.sub-rev-icon',
    compareRevision: '//div[@class="compare-rev-btn flex active"]//h4[text()="Compare Revisions"]',
    variantsIcon: '//div[@data-tip="Product Variants"]',
    newVariantBtn: '.creat-new-variant-link',
    variantsTab: '.tabs-headings [name="variants"]',
    duplicateIcon: '[data-tip="Duplicate a product"]',
    noOfVariants: '.simple-table tbody tr',
    addToChangeOrder: '//span[text()="Add to change order"]',
    viewLatestReleaseBtn: '//button[text()="VIEW LATEST RELEASE"]',
    revertBack: '//*[text()="Revert back"]',
    yesBtnInConfirmRevertChanges: '[class="filled"]',
    exportIconInProductRevisionPage: '.ui-icon[data-tip="Export this Revision"]',
    selectRevisionRadioBtn: '(//div[@class="rounded-checkbox"]/input)[index]'
  },
  updateStatusIcon: '//span[@class="item-title" and text()= "Update Status"]',
  changeStatus: {
    bulkActionStatusChange: '.status-slect.bulk-status.select-status',
    applyBtn: '//button[text()="Apply"]',
    continueIcon: '//div[@class="modal"]//button[text()="Continue"]',
    changeStatus: '#update-revision-holder',
    confirmStatusChangeTable: '#revisionTable',
    statusDropdown: '//tr//*[text()="name"]/ancestor::tr//select[@name="child-status"]',
    tableIndexes: '//div[@id="update-revision-holder"]//table[@id="index-table"]//tbody//tr[indexValue]//input',
    tableRow: '//div[@id="update-revision-holder"]//tr//*[text()="name"]/ancestor::tr',
    includeChildComponents: 'input[name="check-child-revision"]',
    bulkRevision: '.set-bulk-revision-holder .revision-input',
    revisionField: 'input[name="bulk-revision-value"]',
  },
  revertIcon: '//span[@class="item-title" and text()= "Revert"]',
  revertPopup: {
    deleteBtn: 'button.danger',
    yesBtn: '//button[text()="Yes"]',
  },
  resetStatusBtn: '//button[text()="Reset"]',
  commonCheckBoxOptn: '.index-checkbox.block',
  deleteBtnFromTable: '[data-tip="Delete products and components"]',
  duplicateIconFromTable:'#duplicate-icon-new',
  favoriteIcon: '.ui-icon.fav-icon',
  changesWillBeLostModal: '.ui-modal-box .modal',
  cancelBtnInUnsavedChanges: '.button-sections button[class="dark allow"]',
  okBtnInUnsavedChanges: '.button-sections button[class="filled allow"]',
  searchField: 'input[placeholder="Enter a search term or query"]',
  documentsInEditView: {
    revision: '#documentsTable input[name="revision"]',
    statusDropdown: '#documentsTable select[name="status"]',
  },
  vendorLogin: {
    exportIcon: 'div[data-tip="Export this Revision"]',
  },
  documentsInViewPage: {
    documentsTable   : '.documents-view-block #extended-data-table-wrapper tbody',
    documentLink     : (documentName) => `//span[text()="${documentName}"]//ancestor::td/a`,
  },
  compareRevisionsPage: {
    summaryOfChangesPanel: {
      oldRevision: 'div.box-holder.diff-revision-section span.diff-check.remove',
      newRevision: 'div.box-holder.diff-revision-section span.diff-check.add',
      assemblyModifiedlabel: '//div[contains(@class,"diff-assembly-section")]//span[text()="MODIFIED"]',
      assemblyModifiedContent: '//span[text()="MODIFIED"]/ancestor::div[@class="item-list"]//div[@class="item-content"]/span',
    },
    assemblyTable: {
      modifiedRow: '//span[text()="cmpName"]/ancestor::tr[@class="update"]',
      nonModifiedRow: '//span[text()="cmpName"]/ancestor::tr',
      modifiedCount: '//span[text()="cmpName"]/following-sibling::div/div',
      oldRevision: '//span[text()="cmpName"]/ancestor::td/following-sibling::td//div[contains(@class,"update-tag remove")]/span',
      newRevision: '//span[text()="cmpName"]/ancestor::td/following-sibling::td//div[contains(@class,"update-tag add")]/span',
    }
  },
  setNewRevisionsModal: {
    childComponentsTable: '#update-revision-holder',
    allChildCheckBox: 'input[name="group"]',
    childRowCheckBox: '(//span[contains(@class, "index-checkbox")]/input)[Index]'
  },
  productsTable: '.extended-table-data tbody tr',
  totalProductsCount: '.table-icons-section .grey.records-count',
}
