export default {
  newBtn: 'button.new-button',
  firstNameTxtBx: 'input[name="firstName"]',
  lastNameTxtBx: 'input[name="lastName"]',
  emailTxtBx: 'input[name="email"]',
  jobTitleTxtBx: 'input[name="title"]',
  roleDrpDwn: 'select[name="role"]',
  groupCheckbox: 'input[value="groupName"]',
  saveBtn: 'input[type="submit"]',
  tableCell: '//div[text()="email"]/ancestor::tr//td[index]',
  deleteUser: '//div[@id="action-itemId"]//div[text()="Delete user"]',
  modalTitle: '.modal h1',
  modalContent: '.modal h3',
  yesBtn: '.modal button.filled',
  editUserModal: '.modal-content form[class="new-user-form-block"]',
  groupsTab: '//div[@class="nav-block"]/a[text()="groups"]',
  groups: {
    addUserOptionForQa: '//div[text()="QA"]/following-sibling::div/span',
  },
  addUserTxtBx: "//input[@placeholder='Enter name of existing user']",
  checkBx: "//input[@name='group']",
  addUsersBtnInModal: '//input[@value="ADD USERS"]',
  removeUsers: '.remove-col',
  userActionDots: '//span[text()="name"]/ancestor::td/following-sibling::td//div[contains(@class, "action-popover-trigger")]',
  disableUser: '//div[@class="action-pop-item action-popover"]//div[text()="Disable user"]',
  companyProfile: {
    companyName: 'input[name="name"]',
    companyWebsite: 'input[name="website"]',
    addressStreet: 'input[name="address.street"]',
    addressSuite: 'input[name="address.suite"]',
    city: 'input[name="address.city"]',
    state: 'select[name="address.state"]',
    zipCode: 'input[name="address.zip"]',
    country: '//label[text()="Country"]//following-sibling::input[@type="text"]',
    cancelBtn: '.cancel-btn',
    saveBtn: 'input[type="submit"]',
  },
  noOfRowsInUsersTable: 'table.extended-table-data tbody',
  titleTooltip: '//div[contains(@class, "rc-tooltip-inner") and text()="errorTip"]',
  configurationIcon: '//a[text()="configuration"]',
  mandatoryCommentsToggleBtn: '.mandatory-comment [name="toggle-btn"]',
  configuration: {
    mandatoryApprovalTemplatesToggle: '.mandatory-approval div.ui-toggle-btn',
    setUpBtn: '.green.new-button',
    mandatoryTemplatesEditBtn: '.green.new-button',
    templateDropdown: '//td[text()="type"]/following-sibling::td[text()="status"]/following-sibling::td//div[@class="Choose-Template"]',
    approversViewIcon: '//td[text()="type"]/following-sibling::td[text()="status"]/following-sibling::td//div[contains(@class,"approval-modal-visibility")]',
    templateFromDropdown: '//td[text()="type"]/following-sibling::td[text()="status"]/following-sibling::td//div[@class="Choose-Template"]//div[text()="name"]',
    nameInPreviewTemplateModal: '//div[@class="includers-list"]//div/span[text()="name"]',
    clickSaveBtn: '//button[text()="Save"]',
    createNewTemplateInMandatoryApproversDropdown: 'a.open-link-holder',
  },
  sandboxOptn: '.sandbox-and-tutorial',
  usersPageTitle: '//h1[text()="Users"]',
  groupsPageTitle: '//h1[text()="Groups"]',
  groupNameInNewOrEditUserModal: '//span[text()="groupName"]',
  cancelBtnInNewOrEditUserModal: '[value="cancel"]',
  profilePage: {
    role           : 'select[name="role"]',
    email          : 'input[name="email"]',
    saveBtn        : 'input[value="save"]',
    jobTitle       : 'input[name="title"]',
    lastName       : 'input[name="lastName"]',
    firstName      : 'input[name="firstName"]',
    cancelBtn      : '//button[text()="cancel"]',
    phoneNumber    : 'input[name="phoneNumber"]',
    passwordBtn    : 'button[data-testid="password"]',
    selectedRole   : (role) => `select[name="role"]>option[value="${role}"]`,
    oldPassword    : '(//form//input)[1]',
    newPassword    : '(//form//input)[2]',
    confirmLogout  : '//div/button[text()="Logout"]',
  }
}
