export default {
  changeOrderIcon: 'li[id="changeOrderNavLink"] span[class="nav-icon"]',
  newChangeOrder: {
    newBtn: '.green.new-button',
    ecoIcon: 'div[name="eco"]',
    selectAllCheckBx: 'div[class="visible"] div[class="select-all-holder"] div input[type="checkbox"]',
    addBtn:'.btn-add ',
    nameTxtBx: 'input[placeholder="Enter name"]',
    descTxtBx: 'textarea[placeholder="Enter description (optional)"]',
    submitForApproval: 'button[name="submitted"]',
    approveBtn: 'button[name="approve-btn"]',
    rejectBtn: 'button[name="reject-btn"]',
    approvalConfirmationBtn: '//div[@class="button-sections"]/button[text()="APPROVE"]',
    rejectionConfirmationBtn: '//div[@class="button-sections"]/button[text()="REJECT"]',
    closedStatusOptnwithApproval: '.status-item.close-with-approve',
    openStatusOptn: '.status-item.OPEN',
    approvedStatusOptn: '.resolution-btn.APPROVED',
    rejectedStatusOptn: '.resolution-btn.REJECTED',
    approvedDecisionBadge: '.decision-badge .resolution-label.APPROVED',
    rejectedDecisionBadge: '.resolution-label.REJECTED',
    closeBtn: 'button[name="close-btn"]',
    closeConfirmationBtn: '//div[@class="button-sections"]/button[text()="CLOSE"]',
    closedStatusWithRejection: '.status-item.close-with-reject',
    searchBx: '.search-area-holder input',
    updateLoaderHeading: '.validation-heading h4',
    componentCheckBx: '//span[text()="componentName" and @data-name="name"]//ancestor::li//input[@type="checkbox"]',
    tableHeader: '#coListTable th[name="cpn"]',
    tableCell: '//table[@id="coListTable"]//tr//*[text()="name"]/ancestor::tr//td[index]',
    loadingSpinnerOnSearch: '.ci-loading .ui-icon',
    saveDraftBtn: 'button[name="draft"]',
    deleteBtn: '.action-btn.delete-btn',
    confirmDeleteBtn: '//button[normalize-space()="Delete"]',
    changeOrderText: '//h1[normalize-space()="Change Orders"]',
    cancelBtn: '//span[text()="CANCEL"]',
    noneBtn: '.resolution-btn.NONE',
    showMoreBtn: '//div[@class="items-block"]//span[text()=" Show more"]',
    showLessBtn: '//span[text()=" Less"]',
    descriptionBlockInViewMode: '.description-block div.content',
    descriptionBlockInViewMode: '.description-block div.content',
    nameInViewMode: '.name-holder h1',
    editIcon: '.action-btn.edit-btn',
    approverCheckBx: '//span[text()="approverName"]//ancestor::span//preceding-sibling::span/input[@type="checkbox"]',
    approverType: 'input[type="checkbox"][name=approverType]',
    saveAsNewTemplate: 'input[name="save-template"]',
    saveBtnInCreatingTemplate: '.spinner-btn',
    approverSearchBx: 'input[placeholder="Enter existing user"]',
    addBtnInApprovers: '.btn-add.enabled',
    templateDropdown: '//div[contains(@class,duro_menu)]//div[text()="category"]//parent::div//div[text()="templateName"]',
    templateDropdownBar: '.duro__indicator.duro__dropdown-indicator',
    templateSettings: '.manage-templates div[data-tip="Template Settings"]',
    notificationListTab: '//h2[text()="Notification List"]',
    approverCheckBx: '//span[text()="approverName"]//ancestor::span//preceding-sibling::span/input[@type="checkbox"]',
    approverSearchBx: 'input[placeholder="Enter existing user"]',
    addBtnInApprovers: '.btn-add.enabled',
    templateDropdown: '//div[contains(@class,duro_menu)]//div[text()="category"]//parent::div//div[text()="templateName"]',
    approversList: '.visible .list-area',
    manageTemplatesModal: '.modal-body',
    emailInNotificationList: '#right-side_bar-content textarea[type="text"]',
    addEmailBtn: '.add-email-btn',
    okBtnInModal: 'button[class="filled allow"]',
    approverListTab: '//div[contains(@class,"tabs-block")]//h2[text()="Approver List"]',
    searchForApprover: '//*//input[@placeholder="Enter existing user"]',
    addBtnFromApproverList: '.btn-add.enabled',
    saveTemplateIcon: '.show-save',
    saveOrUpdateTemplate: '.modal-body',
    TemplateNameInSaveAsNewTemplate: '[name="save-template"]',
    saveBtnInSaveOrUpdateTemplateModal: '.spinner-btn',
    privateTemplate: '//div[@class="modal-content"]//h3[text()="PRIVATE TEMPLATES"]//parent::div//div[contains(@class,"modal-body-content")]//div[text()="templateName"]',
    companyTemplate: '//div[@class="modal-content"]//h3[text()="COMPANY TEMPLATES"]//following-sibling::div//div[text()="templateName"]',
    dropdownIndicator: '#right-side_bar-content .duro__dropdown-indicator',
    dropdownTemplate: '//div[contains(@class, "duro__menu")]//div[text()="one user template"]',
    removeInManageTemplatesModal: '//div[text()="templateName"]/div',
    deleteTemplateBtn: '.delete',
    saveBtnInManageTemplates: '//button[text()="SAVE"]',
    cancelBtnInManageTemplates: '.dark',
    deleteTemplateModal: '.delete-warning-modal .modal-heading h3',
    cancelBtnInDeleteTemplateModal: '//div[@class="delete-warning-modal"]/div//button[@class="dark"]',
    cancelBtnInEditMode: '.banner-btn-holder span',
    modal: '.modal',
    dropdownIndicatorInModal: '//div[@class="existing-templates"]/child::div//div[contains(@class,"duro__indicators")]',
    accessibleToAllCheckBx: 'input[name="check-row"]',
    toolTip: '//div[@class="description-tip"]//span[text()="assertText"]',
    selectAllApprovers: '#right-side_bar-content .select-all-holder [type="checkbox"]',
    nextRevision: '//*[text()="name"]//ancestor::tr//*[contains(@class,"revision-label text ")]',
    statusValueInChangeOrderTable: '//*[text()="name"]//ancestor::tr//span[@class="status-holder"]//span[@class="status-value"]',
    revisionActionIcon: '[data-tip="Revision Actions"]',
    majorRevisionType: '.rev-action-modal input[name="major"]',
    minorRevisionType: '.rev-action-modal input[name="minor"]',
    customRevisionType: '.rev-action-modal input[name="custom"]',
    applyBtnInChangeRevisionModal: '//button[text()="Apply"]',
    customRevision: 'input[name="custom-rev-input"]',
    changeOrderTableRow: '//tr//*[text()="name"]/ancestor::tr',
    changeOrderTableIndexes: '//table[@id="index-table"]//tbody//tr[1]//div',
    customRevisionTooltipInCoTable: '.description-tip.invalid span',
    statusInTable: '//span[@class="status-holder"]//span[@class="status-value"]',
    dcoIcon: 'div[name="dco"]',
    searchTemplate: '.template-select input',
    manageTemplateModalTitle: '.manage-templates-modal .modal-heading h3',
    approverListPage: '//h2[text()="Add Approvers to Change Order"]',
    notificationListPage: '//h2[text()="Add Users to Notify"]',
    commentInConfirmDecisionCoModal: '.warning-text textarea',
    draftStatusOptn: '.status-item.DRAFT',
    tableIndex: '#coListTable',
    previousRevision: '//*[text()="name"]//ancestor::tr//span[contains(@class," default-rev-scheme")]/span',
    approverDeleteIcon: '//span[text()="approverName"]//ancestor::tr//div[@data-tip="Remove from Change Order"]',
    modalSubHeading: '.modal-content h3',
    cancelBtnInConfirmDescisionModal: '//div[@class="modal"]//button[text()="Cancel"]',
    mcoIcon: 'div[name="mco"]',
    dcoIcon: 'div[name="dco"]',
    okBtnInDcoWarningModal: '.filled.allow',
    selectedTemplate: 'div.template-select',
    productsAndComponentsTab: '.prd-cmp-holder',
    removeIconInNewCoForProdOrCmp: '//*[text()="name"]//ancestor::tr//div[@data-tip="Remove from Change Order"]',
    mandatoryTemplateModal: 'div.ui-modal-box div.modal',
    mandatoryTemplateModalHeading: 'div.ui-modal-box div.modal .header-block h2',
    mandatoryTemplateModalContent: '.rules-list',
    gotItBtnInmandatoryTemplateModal: '.save-button',
    mandatoryTemplateToastHeading: '.popover-heading',
    mandatoryTemplateToastTemplateName: '.popover-content-body',
    removeIconForTemplate: '//div[text()="name"]/div[contains(@class,"remove-template")]',
    updateStatusIcon: 'span[data-tip="Update Status"]',
    changeOrderTableIndex: '(//table[@id="index-table"]//tbody//tr)[1]',
    productsAndComponentsList: '.modal .list-area',
    componentValidationSpinner: '.open.validation-running',
    selectAllCheckBxInAssemblyTable: 'input[name="group"]',
    resetBtn: '//button[text()="Reset"]',
    assemblyLibraryCpn: '.list-area .cpn',
    includeChildrenComponentsCheckBox: 'input[name="include-children"]',
    cmpOrProductNameInCoTable: '//table[@id="coListTable"]//*[text()="name"]',
    cmpOrProductNameInCoSearchList:'//span[text()="cmpName"]',
  },
  statusValueInChangeOrderTable: '//*[text()="name"]//ancestor::tr//span[@class="status-holder"]//span[@class="status-value"]',
  selectedStatusValueInChangeOrderTable: '//*[text()="name"]//ancestor::tr//span[@class="status-label"]//option[normalize-space()="statusName"]',
  viewChangeOrder: {
    resendChangeOrderIcon: 'button.action-btn.resend-email',
    history: '//h2[text()="History"]',
    changeOrderName: '//div[@class="co-properties"]//tr/th[text()="CON:"]/following-sibling::td',
    editBtn: '.action-btn.edit-btn',
    deleteBtn: '.action-btn.delete-btn',
    noOfChildren: '.index-table tbody tr',
    table_CPN: (name) => `//div[text()="${name}"]//ancestor::tr//span[@class="cpn-value"]`,
    statusValue: (name) =>`//*[text()="${name}"]//ancestor::tr//span//select[@name="status"]//option[@value="statusName"]`
  },
  approverList: {
    approverTableRemoveIconHeader: 'table#co-approver-list-table th[name="remove"]',
    approverRemoveIcon:'//table[@id="co-approver-list-table"]//span[text()= "name"]/ancestor::tr//td[index]//div[@class="ui-icon "]',
  },
  notifierList: {
    notifierTableRemoveIconHeader: 'table#coListTable th[name="remove"]',
    notifierRemoveIcon: '//table[@id="coListTable"]//span[text()= "name"]/ancestor::tr//td[index]//div[@class="ui-icon "]',
  },
  resendChangeOrderModal: {
    approverCheckBox: 'input[name=approvers]',
    notifierCheckBox: 'input[name=notifiers]',
    ccMailTxtBx: '//input[contains(@placeholder,"Enter email addresses")]',
    addBtnForCcMail: '.action-button',
    resendBtn: '//button[text()="Resend"]',
    crossBtnInPrepareCOMailModal: '.buttons.modal-close',
    verifyCcEmail: '//a[text()="email"]//ancestor::div[@class="item"]//span[text()="Anonymous"]',
    mailSentModal: '.email-sent-block',
    removeIconInResendEcoModal: '//div[@class="item"]/child::div[@class="ui-icon "]',
    resendChangeOrderModalTitle: '.modal-content h1',
    cancelBtn: '//button[text()="Cancel"]',
    user: '//span[@class="name"][text()="userName"]',
  },
  changeStatus: {
    modalTitle: '//h1[text()="Confirm status change"]',
    bulkStatus: '.bulk-status.select-status',
    bulkRevision: '.set-bulk-revision-holder .revision-input',
    applyBtn: '//button[text()="Apply"]',
    continueBtn: '//button[text()="Continue"]',
    currentStatus: '//table[@id="revisionTable"]//div[text()="cmpName"]//ancestor::tr//span[text()="STATUS"]',
    newStatus: '//table[@id="revisionTable"]//div[text()="cmpName"]//ancestor::tr//option[text()="STATUS"]',
    currentRevision: '//table[@id="revisionTable"]//div[text()="cmpName"]//ancestor::tr//span[@class="revision-value"]',
    newRevision: '//table[@id="revisionTable"]//div[text()="cmpName"]//ancestor::tr//input',
    newRevisionBeforeUpdate: (name) => `//table[@id="revisionTable"]//div[text()="${name}"]//ancestor::tr//div[contains(@class, "revision-label")]`,
  },
  changeOrderTable: {
    lastReleaseStatus: '//div[text()="cmpName"]//ancestor::tr//td[@class="last-release-cell"]//span[contains(@class,"status-label")]',
    lastReleaseRevision: '//div[text()="cmpName"]//ancestor::tr//td[@class="last-release-cell"]//span[contains(@class,"revision-value")]',
    newStatus: '(//div[text()="cmpName"]//ancestor::tr//span[@class="status-holder"]//span[text()="STATUS"])[1]',
    newRevision: '(//div[text()="cmpName"]//ancestor::tr//span[@class="revision-value" and text()="REV"])[1]',
    cpn: '//tr//*[text()="name"]/ancestor::tr//td//a/span[index]'
  }
}
